name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    run-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build the Notely app
        run: ./scripts/buildprod.sh
