name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build the Notely app
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
     
      - name: Build the image and upload it to registry
        run: 'gcloud builds submit --tag europe-west10-docker.pkg.dev/notely-445507/notely-ar-repo/notely:latest'

      - name: Deploy to Cloud Run
        run: 'gcloud run deploy notely --image europe-west10-docker.pkg.dev/notely-445507/notely-ar-repo/notely@sha256:2ccb968a5780821bf310c23634fb3b60d0cb6d997bb668f2f7914043d94ba1f9 --region us-central1 --allow-unauthenticated --project notely-445507 --max-instances=4'
